# Development Environment Configuration
# Testnet + Live Trading (for development)
# Extends: base.yml

extends: base.yml

system:
  environment: development
  debug: true
  health_check_interval: 600  # 10 minutes
  memory_threshold_mb: 512

binance:
  testnet: true
  base_url: https://testnet.binance.vision

discord:
  channel_id: 0  # Disabled for local development
  enable_notifications: false
  spam_protection_seconds: 30

logging:
  level: DEBUG
  format: text
  output_dir: logs
  max_bytes: 5242880  # 5MB
  backup_count: 3
  debug_unmask: true  # Allow unmasking in debug mode

trading:
  max_position_size: 0.01  # Small size for testing
  max_risk_per_trade: 0.01  # 1% max risk
  daily_loss_limit: 0.03  # 3% daily limit

data:
  cache_size: 500
  historical_lookback_days: 30

risk:
  max_position_size_pct: 0.05
  max_drawdown_pct: 0.15

execution:
  slippage_tolerance_pct: 0.002  # 0.2%

custom:
  dry_run: false
  mock_api: false
  enable_backtesting: true
