# Development Environment Configuration
# For local development and testing

system:
  environment: development
  debug: true
  async_workers: 2
  health_check_interval: 600  # 10 minutes
  memory_threshold_mb: 512

binance:
  api_key: ${TRADING_BINANCE_API_KEY}
  api_secret: ${TRADING_BINANCE_API_SECRET}
  testnet: true
  base_url: https://testnet.binance.vision

discord:
  bot_token: ${TRADING_DISCORD_BOT_TOKEN}
  channel_id: ${TRADING_DISCORD_CHANNEL_ID}
  enable_notifications: true
  spam_protection_seconds: 30

logging:
  level: DEBUG
  format: json
  output_dir: logs
  
  # Rotation settings (smaller for dev)
  max_bytes: 5242880  # 5MB
  backup_count: 3
  rotation_time: midnight
  
  # Trade logs
  trade_log_enabled: true
  trade_log_file: trades.log
  
  # Performance logs
  performance_log_enabled: true
  performance_log_file: performance.log
  
  # Sensitive data masking (relaxed for dev)
  mask_sensitive_data: true
  debug_unmask: true  # Allow unmasking in debug mode

trading:
  symbol: BTCUSDT
  timeframe: 1h
  max_position_size: 0.01  # Small size for testing
  leverage: 1
  
  # Risk management (conservative for dev)
  max_risk_per_trade: 0.01  # 1% max risk
  daily_loss_limit: 0.03  # 3% daily limit

custom:
  # Add any custom development-specific settings here
  mock_api: false
  enable_backtesting: true