# Paper Trading Environment Configuration
# For simulated trading with real market data

system:
  environment: paper
  debug: false
  async_workers: 2
  event_queue_size: 1000
  health_check_interval: 300  # 5 minutes
  memory_threshold_mb: 1024

binance:
  api_key: ${TRADING_BINANCE_API_KEY}
  api_secret: ${TRADING_BINANCE_API_SECRET}
  testnet: true  # Use testnet for paper trading
  base_url: https://testnet.binance.vision

discord:
  bot_token: ${TRADING_DISCORD_BOT_TOKEN}
  channel_id: ${TRADING_DISCORD_CHANNEL_ID}
  enable_notifications: true
  spam_protection_seconds: 60

logging:
  level: INFO
  format: json
  output_dir: logs/paper
  
  # Rotation settings
  max_bytes: 10485760  # 10MB
  backup_count: 5
  rotation_time: midnight
  
  # Trade logs
  trade_log_enabled: true
  trade_log_file: paper_trades.log
  
  # Performance logs
  performance_log_enabled: true
  performance_log_file: paper_performance.log
  
  # Sensitive data masking
  mask_sensitive_data: true
  debug_unmask: false

trading:
  symbol: BTCUSDT
  timeframe: 1h
  max_position_size: 0.1
  leverage: 2
  
  # Risk management (realistic settings)
  max_risk_per_trade: 0.02  # 2% max risk
  daily_loss_limit: 0.05  # 5% daily limit

# Data layer configuration
data:
  cache_size: 1000
  cache_ttl: 300  # 5 minutes
  historical_lookback_days: 60

# Risk management configuration
risk:
  initial_capital: 25000.0  # Paper trading capital
  max_position_size_pct: 0.1
  max_drawdown_pct: 0.2
  max_consecutive_losses: 3
  volatility_threshold: 0.05

# Strategy configuration
strategy:
  enabled_strategies:
    - ict
    - traditional
  default_strategy: ict
  strategy_selection_mode: auto

# Execution configuration
execution:
  slippage_tolerance_pct: 0.001  # 0.1%
  max_retry_attempts: 3
  order_timeout_seconds: 30

# System events configuration
system_events:
  event_queue_size: 1000
  message_hub_max_subscribers: 100

custom:
  # Paper trading specific settings
  simulate_slippage: true
  simulate_fees: true
  track_performance: true
  dry_run: false  # Execute on testnet
  paper_mode: true
