# Paper Trading Environment Configuration
# For simulated trading with real market data
# Extends: base.yml

extends: base.yml

system:
  environment: paper

logging:
  output_dir: logs/paper
  trade_log_file: paper_trades.log
  performance_log_file: paper_performance.log

initial_capital: 25000.0

custom:
  # Paper trading specific settings
  simulate_slippage: true
  simulate_fees: true
  track_performance: true
  dry_run: false  # Execute on testnet
  paper_mode: true
