# Production Environment Configuration
# For live trading with real funds

system:
  environment: production
  debug: false
  async_workers: 4
  health_check_interval: 300  # 5 minutes
  memory_threshold_mb: 1024

binance:
  api_key: ${TRADING_BINANCE_API_KEY}
  api_secret: ${TRADING_BINANCE_API_SECRET}
  testnet: false
  base_url: null  # Use default production URL

discord:
  bot_token: ${TRADING_DISCORD_BOT_TOKEN}
  channel_id: ${TRADING_DISCORD_CHANNEL_ID}
  enable_notifications: true
  spam_protection_seconds: 60

logging:
  level: INFO
  format: json
  output_dir: logs
  
  # Rotation settings
  max_bytes: 10485760  # 10MB
  backup_count: 10
  rotation_time: midnight
  
  # Trade logs
  trade_log_enabled: true
  trade_log_file: trades.log
  
  # Performance logs
  performance_log_enabled: true
  performance_log_file: performance.log
  
  # Sensitive data masking (strict in production)
  mask_sensitive_data: true
  debug_unmask: false  # Never unmask in production

trading:
  symbol: BTCUSDT
  timeframe: 1h
  max_position_size: 0.1
  leverage: 1
  
  # Risk management
  max_risk_per_trade: 0.02  # 2% max risk
  daily_loss_limit: 0.05  # 5% daily limit

custom:
  # Production-specific settings
  enable_monitoring: true
  alert_on_error: true