# Production Environment Configuration
# Mainnet + Live Trading
# Extends: base.yml

extends: base.yml

system:
  environment: production
  debug: false
  async_workers: 4
  event_queue_size: 2000
  memory_threshold_mb: 2048

binance:
  testnet: false
  base_url: https://api.binance.com

logging:
  level: INFO
  format: json
  output_dir: /var/log/trading-bot
  max_bytes: 52428800  # 50MB
  backup_count: 10

trading:
  leverage: 3

data:
  cache_size: 2000
  cache_ttl: 600  # 10 minutes
  historical_lookback_days: 90

risk:
  initial_capital: 50000.0

execution:
  max_retry_attempts: 5
  order_timeout_seconds: 60

system_events:
  event_queue_size: 2000
  message_hub_max_subscribers: 200

custom:
  dry_run: false
  enable_monitoring: true
  enable_alerts: true
